{% set version = "3.0.9" %}

package:
  name: ipart
  version: {{ version }}

source:
  url: https://github.com/ihesp/IPART/archive/v{{ version }}.tar.gz
  sha256: 77f320d361aa8f2ac85eda77e0c5fc72ff7e4cf7474219076d967007fefb52f4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - netcdf4
    - scikit-image
    - networkx
    - matplotlib-base

test:
  imports:
    - ipart
    - ipart.utils
  source_files:
    - tests
  commands:
    - python -m unittest discover -s tests

about:
  home: https://github.com/ihesp/IPART
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'IPART is a Python package for the detection and tracking of atmospheric rivers from gridded IVT data using image-processing techniques'
  description: |
    IPART is a Python package for the detection and tracking of atmospheric
    rivers from gridded (Integrated Vapor Transport) IVT data using image-processing techniques
  doc_url: https://ipart.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - Xunius
